#include <android/log.h>
#include <jni.h>
#include <thread>
#include <time.h>

#include "hooks/dlsym_hook.h"
#include "hooks/shithook.hpp"
#include "utils/utils.h"

#define LOGI( ... ) ( ( void )__android_log_print( ANDROID_LOG_INFO, "ligma", __VA_ARGS__ ) )
#define LOGW( ... ) ( ( void )__android_log_print( ANDROID_LOG_WARN, "ligma", __VA_ARGS__ ) )

// https://man7.org/linux/man-pages/man5/elf.5.html
// init is invoked by the dynamic linker as its considered part of the "initalization code"
//
// the elf file generated by ndk compiler will create a .init section...
__attribute__( ( constructor ) ) void init()
{
    LOGI( "ligma cheat loaded!" );
    ligma::utils::on_image_load( "libil2cpp.so", [ & ]( std::uintptr_t module_base, void *module_handle ) -> bool {
        LOGI( "libil2cpp base = %p", module_base );
        return false;
    } );
}